version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  web:
    build: .
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    volumes:
      - .:/backend
    ports:
      - '3010:3010'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
